FROM debian:13

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        php-fpm \
        curl \
        unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

# Télécharger et installer WordPress
RUN curl -O https://wordpress.org/latest.zip \
    && unzip latest.zip \
    && mv wordpress/* . \
    && rm -rf wordpress latest.zip

# Définir les bons droits
RUN chown -R www-data:www-data /var/www/html

CMD ["php-fpm8.2", "-F"]