services:
  web:
    image: wordpress:latest
    networks:
      - home
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mariadb:latest
    networks:
      - home
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress

  nginx:
    image: nginx:latest
    networks:
      - home
    restart: always
    depends_on:
      - web
    ports:
      - "8080:80"   # Port HTTP
      - "8443:443"  # Port HTTPS
    volumes:
      - ./requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs  # Montage des certificats SSL

networks:
  home:
    driver: bridge

volumes:
  db_data:
