services:
  web:
    image: wordpress:latest
    networks:
      - home
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    secrets:
      - wordpress_db_password
      - mysql_root_password

  db:
    image: mariadb:latest
    networks:
      - home
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wordpress_db_password
    secrets:
      - mysql_root_password
      - wordpress_db_password

  nginx:
    build: requirements/nginx/
    networks:
      - home
    restart: always
    depends_on:
      - web
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./requirements/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs 

secrets:
  mysql_root_password:
    file: ../secrets/mysql_root_password
  wordpress_db_password:
    file: ../secrets/wordpress_db_password

networks:
  home:
    driver: bridge

volumes:
  db_data:
