services:
  web:
    build: wordpress:latest
    networks:
      - home
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example

  db:
    image: mariadb:latest
    networks:
      - home
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress

networks:
  home:
    driver: bridge
  
volumes:
  db_data: